### PR TITLE
Added Options for LiveQuery

### PR DESCRIPTION
**Pull request by AliabbasMerchant**
@YourTechBud Done

### CODE REVIEW

**Comment by AliabbasMerchant** [comment]
@YourTechBud This is proper. Does not need to be changed.

**Comment by YourTechBud** [comment]
@AliabbasMerchant you have included the `skipInitial` and `changesOnly` in the `subscribe` function. You need to add a `.options()` to accept these values

**Comment by AliabbasMerchant** [comment]
@YourTechBud I do not think a separate options function is required in python. These arguments are optional, and python coders are comfortable using such optional (keyword) arguments.

**Comment by YourTechBud** [comment]
For consistency lets keep a options functions. Let options take keyword parameters.

**Comment by AliabbasMerchant** [comment]
@YourTechBud  Done

**Comment by YourTechBud** [comment]
By default, neglect initial should be false. We want to get the result set by default

**Comment by AliabbasMerchant** [comment]
@YourTechBud I have made the latest changes in accordance with the changes on SC

**Comment by YourTechBud** [comment]
@AliabbasMerchant I've requested some changes in sc. See if it works with that too

**Comment by AliabbasMerchant** [comment]
Yup. Works! 🚀

**Pull request merged**
