### PR TITLE
changed the update method to append clause to the dict(fixes #18)

### LINKED ISSUE #18: Conditions for the same field gets overwritten
```js
where(and(cond('a', '>=', 'somevalue'), cond('a', '<=', 'someothervalue')))
```
For the above example only the second condition is reflected because the first gets overwritten by the second condition

### PR DESCRIPTION
**Pull request by VedantParanjape**
Conditions for the same field gets overwritten #18

### CODE REVIEW

**Comment by VedantParanjape** [comment]
Then, with dict this issue cannot be solved?
@AliabbasMerchant

**Comment by VedantParanjape** [comment]
> Python conventions recommend snake_case, not CamelCase. Use that.

done with this

**Comment by AliabbasMerchant** [comment]
Use a list as the value of the dict.  
`d["a"] = ["b", "c"]`  
Then
```
for k, v in new_dict.items():
  if d.get(k) is not None:
    d[k] = list(d[k])
    d[k].append(v)
  else:
    d[k] = v
```

But then you will have to accordingly send info in the transport module (depending on the value being a list or a string)

**Comment by YourTechBud** [comment]
@AliabbasMerchant I'll merge this request once you approve it. The problem arises when two different conditions are put with the same `f1` value. Eg. `where(and(cond('a', '>=', 'somevalue'), cond('a', '<=', 'someothervalue')))`

The result data structure should look like this:
```js
{
  a: {
    $gte: someValue,
    $lte: someOtherValye
  }
}
```
@Jayesh333 Am i right?

**Comment by AliabbasMerchant** [comment]
If we need a data structure such as:   
```
{
  a: {
    $gte: someValue,
    $lte: someOtherValye
  }
}
```

And if we have a single condition will it be like this?:
```
{
  a: {
    $gte: someValue
  }
}
```

Then we need to use a nested dict. Not a list
Also, we will need to update the same thing for the OR condition.

**Comment by VedantParanjape** [comment]
> If we need a data structure such as:
> 
> ```
> {
>   a: {
>     $gte: someValue,
>     $lte: someOtherValye
>   }
> }
> ```
> 
> And if we have a single condition will it be like this?:
> 
> ```
> {
>   a: {
>     $gte: someValue
>   }
> }
> ```
> 
> Then we need to use a nested dict. Not a list
> Also, we will need to update the same thing for the OR condition.

OR condition is correct? It doesn't have that rewrite issue !!

**Comment by YourTechBud** [comment]
Or condition is correct since its an array. The problem is only with and.

**Comment by YourTechBud** [comment]
@AliabbasMerchant why don't you take over this one?

**Comment by AliabbasMerchant** [comment]
Ok

**Comment by YourTechBud** [comment]
@AliabbasMerchant Whats the status on this one?

**Comment by AliabbasMerchant** [comment]
I will do this hopefully by 4th June evening

**Pull request closed without merging**
